FROM node:6.13.1-alpine@sha256:90ab70c875be439778a6e644b972d0b99a1cbebc42b74cb65c998e02004131f8

LABEL maintainer "Leonardo Gatica <lgatica@protonmail.com>"

RUN apk add --no-cache --virtual build-dependencies make gcc g++ python && \
  apk add --no-cache krb5-dev

CMD [ "node" ]
