FROM lgatica/node-krb5:7.5.0

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

ONBUILD ARG NODE_ENV
ONBUILD ENV NODE_ENV $NODE_ENV
ONBUILD COPY package.json /usr/src/app/
ONBUILD RUN npm install && npm cache clean && apk del build-dependencies
ONBUILD COPY . /usr/src/app

CMD [ "npm", "start" ]
